config/routes.rb
Rails.application.routes.draw do
  resources :plans do
    collection do
      get 'list_index'
    end
  end
  devise_for :users,
   controllers: { registrations: 'users/registrations' }
  root to: "plans#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :title, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :nickname, :encrypted_password, presence: true
  has_many  :plans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :list_plan, only: [:list_index]
  before_action :Guard_clause, only: [:show,]

  # GET /plans
  # GET /plans.json
  def index
    @search = Plan.ransack(params[:q])
    @plans = @search.result
  end

  def list_index
    @search = Plan.ransack(params[:q])
    @plans = @search.result
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.create(plan_params)
    redirect_to plans_path
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    if @plan.update(plan_params)
      redirect_to plans_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    redirect_to  list_index_plans_path, notice:"削除しました"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    def list_plan
      @plans = Plan.includes(:user)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:title, :content, :image, :start_time).merge(user_id: current_user.id)
    end

    def month_plans_params
      params.require(:plan).permit!
    end

    def Guard_clause
      if @plan.user_id != current_user.id
        flash[:alert]= 'ユーザーが違います'
        redirect_to root_path
      end
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 毎日日記
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    %header.header
      .header__title
        = link_to "毎日日記", root_path, class: "header__title__text"
      .header__right
        - if user_signed_in?
          =current_user.nickname
          
          = link_to edit_user_registration_path, class: "header__right__icon" do
            = icon('fas', 'users-cog')
          = link_to  new_plan_path, class: "header__right__icon" do
            = icon('fas', 'pencil-alt')
          = link_to  list_index_plans_path, class: "header__right__icon" do
            = icon("fas", "list-ul")
          = link_to destroy_user_session_path, method: :delete, class: "header__right__icon" do
            = icon('fas', 'door-open')
        - else
          = link_to "ログイン", new_user_session_path, class: "header__btn"
          = link_to "新規登録", new_user_registration_path, class: "header__btn"
    = yield

app/views/message/new.html.haml
.content__title
  新規記事の作成
.main__post
  = form_with model: @messages, class: :form, local: true do |form|
    = form.text_field :title, placeholder: :タイトル, class: ":form__title"
    = form.text_field :image, placeholder: "Image Url", class: "form__image"
    = form.text_area :text, placeholder: :ブログ本文, class: ":form__text"
    = form.submit '投稿する', class: ":form__btn"

app/views/plans/_form.html.haml
= form_for @plan do |f|
  - if @plan.errors.any?
    #error_explanation
      %h2= "#{pluralize(@plan.errors.count, "error")} prohibited this plan from being saved:"
      %ul
        - @plan.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label "予定"
    = f.text_field :title
  .field
    = f.label "開始時間"
    = f.datetime_select :start_time
  -# .actions
    = f.submit '登録'

app/views/plans/edit.html.haml
= image_tag 'image8.jpg', class: 'main-image2'

.post-main
  %h1 投稿編集
  = form_for @plan do |f|
    %table
      %tr
        %th
          = f.label 'タイトル', class: 'post-main_logo'
        %th
          = f.text_field :title, class: 'post-main_title'
          
      %tr
        %th
          = f.label '日時', class: 'post-main_logo'
        %th
          = f.datetime_select :start_time, class: 'post-main_time'

      %tr
        %th
          = f.label '画像', class: 'post-main_logo'
        %th 
          #img_field{:onclick => "$('#file').click()"}
            - if @plan.image.present?
              = image_tag @plan.image.url, size: '200x150'
            - else
              %i.fas.fa-image
              %i.fas.fa-file-upload.add
          // id "file"をつけ、「display:none;」で隠す
          =f.file_field :image, class: "image", style: "display:none;", id: "file"

      %tr
        %th
          = f.label '内容', class: 'post-main_logo'
        %th
          = f.text_area :content, class: 'post-main_content'

    = f.submit '更新', class: 'post-main_btn'

app/views/plans/index.html.haml
- if user_signed_in?
  .main-page
    = month_calendar events: @plans do |date, plans|
      = date.day

      .main-page_schedule
        -plans.each do |plan|
          -if plan.user_id == current_user.id
            %ol
              %li= link_to plan.title, plan, class: 'main-page_schedule_name'
- else
  .main-page
    = month_calendar events: @plans do |date, plans|
      = date.day

app/views/plans/index.html.haml+smart.erb
- if user_signed_in?
  .main-page
    = month_calendar events: @plans do |date, plans|
      = date.day

      .main-page_schedule
        -plans.each do |plan|
          -if plan.user_id == current_user.id
            %ol
              %li= link_to plan.title, plan, class: 'main-page_schedule_name'
- else
  .main-page
    = month_calendar events: @plans do |date, plans|
      = date.day

app/views/plans/list_index.html.haml
.main-logo
  .main-logo_post
    検索
    = search_form_for(@search, url: list_index_plans_path) do |f|
      .main-logo_post_group
        = f.label :title, "タイトル：", class: "main-logo_post_letter"
        = f.text_field :title_cont, class: "main-logo_post_control"
      .main-logo_post_group
        = f.label :start_time, "日付開始：", class: "main-logo_post_letter"
        = f.date_select :start_time_gteq, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, class: "main-logo_post_control2"
      .main-logo_post_group
        = f.label :start_time, "日付終了：", class: "main-logo_post_letter"
        = f.date_select :start_time_lteq_end_of_day, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, class: "main-logo_post_control2"
      .main-logo_post_actions
        = f.submit "検索", class: "main-logo_post_sub"
  .main-logo_post
    日記一覧
    .main-logo_post_table
      %table
        %thead
          %tr
            %th
              .main-logo_post_info
                タイトル
            %th
              .main-logo_post_info
                ユーザー名
            %th
              .main-logo_post_info
                日時
        %tbody
          -@plans.each do |plan| 
            -if plan.user_id == current_user.id
              %tr
                %td 
                  = link_to plan.title, plan_path(plan.id), class: 'main-logo_post_btn'
                %td
                  =plan.user.nickname
                %td
                  = plan.start_time.strftime("%Y年%m月%d日")

app/views/plans/new.html.haml
= image_tag 'image3.jpg', class: 'main-image2'
.post-main
  %h1 新規投稿
  = form_for @plan do |f|
    %table
      %tr
        %th
          = f.label 'タイトル', class: 'post-main_logo'
        %th
          = f.text_field :title, class: 'post-main_title'

      %tr
        %th
          = f.label '日時', class: 'post-main_logo'
        %th
          = f.datetime_select :start_time, use_month_numbers: true, class: 'post-main_time'

      %tr
        %th
          = f.label '画像', class: 'post-main_logo'
        %th 
          #img_field{onclick: "$('#file').click()"}
            - if @plan.image.present?
              = image_tag @plan.image
            - else
              %i.fas.fa-image
              %i.fas.fa-file-upload.add
          // id "file"をつけ、「display:none;」で隠す
          =f.file_field :image, class: "image", style: "display:none;", id: "file"

      %tr
        %th
          = f.label '内容', class: 'post-main_logo'
        %th
          = f.text_area :content, class: 'post-main_content'

    = f.submit '登録', class: 'post-main_btn'

app/views/plans/show.html.haml
= image_tag 'image5.jpg', class: 'main-top'

.main-info
  .main-info_sel
    .main-info_sel_content
      内容詳細
    = link_to '編集', edit_plan_path(@plan), class: "main-info_sel_btn"
    = link_to '戻る', plans_path, class: "main-info_sel_btn"
    = link_to '削除',plan_path(@plan), method: :delete, id: 'item-delete-btn', class: 'main-info_sel_btn',  data:{ confirm: '本当に削除しても良いですか?',cancel: 'キャンセル',commit: '削除する'}, title: '削除確認！'

  %table
    %tr
      %th
        .main-info_title
          タイトル
      %th
        .main-info_logo
          = @plan.title

    %tr
      %th
        .main-info_title
          日時
      %th
        .main-info_logo
          = @plan.start_time.strftime("%Y年%m月%d日 %H:%M")

    %tr
      %th
        .main-info_title
          画像
      %th
        -if  @plan.image.present?
          = image_tag @plan.image.url, class: "main-info_image"
        - else
          = image_tag "image1.png", class: "main-info_image"

    %tr
      %th
        .main-info_title
          内容
      %th
        .main-info_message
          =simple_format(@plan.content)

app/views/simple_calendar/_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: '前月'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.abbr_month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: '次月'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        = content_tag :tr, class: calendar.tr_classes_for(week) do
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml(day, sorted_events.fetch(day, []), &block)
              - else
                - block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_month_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: '前月'), calendar.url_for_previous_view, class: 'calendar-heading_btn'
    %span.calendar-title
      = start_date.year
      年 #{t('date.abbr_month_names')[start_date.month]}
    = link_to t('simple_calendar.next', default: '次月'), calendar.url_for_next_view, class: 'calendar-heading_btn'
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml(day, sorted_events.fetch(day, []), &block)
              - else
                - block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_week_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    - if calendar.number_of_weeks == 1
      %span.calendar-title
        Week #{calendar.week_number}
    - else
      %span.calendar-title
        Week #{calendar.week_number} - #{calendar.end_week}
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml(day, sorted_events.fetch(day, []), &block)
              - else
                - block.call day, sorted_events.fetch(day, [])